# Generated by Django 5.0.6 on 2024-10-02 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='si',
            name='comment',
            field=models.TextField(default='none', verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='years', to='device.year', verbose_name='Год выпуска'),
        ),
    ]
