# Generated by Django 5.0.6 on 2024-10-02 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_si_comment_alter_equipment_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='si',
            old_name='comment',
            new_name='com',
        ),
    ]
