# Generated by Django 5.0.6 on 2025-10-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0025_files_alter_manual_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gp',
            options={'ordering': ['ordering']},
        ),
        migrations.AddField(
            model_name='gp',
            name='ordering',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
