# Generated by Django 5.0.6 on 2024-10-22 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='ФИО утв.')),
                ('job_title', models.CharField(max_length=50, verbose_name='Должность')),
                ('organization', models.CharField(max_length=100, verbose_name='Организация')),
            ],
            options={
                'verbose_name_plural': 'Утверждающие',
            },
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='ФИО подряднчика')),
                ('job_title', models.CharField(max_length=50, verbose_name='Должность')),
                ('organization', models.CharField(max_length=100, verbose_name='Организация')),
            ],
            options={
                'verbose_name_plural': 'Подрядные организации',
            },
        ),
        migrations.CreateModel(
            name='Kait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='ФИО мастера Каит')),
                ('job_title', models.CharField(max_length=50, verbose_name='Должность')),
                ('organization', models.CharField(max_length=100, verbose_name='Организация')),
            ],
            options={
                'verbose_name_plural': 'Мастера КАиТ',
                'ordering': ('-job_title',),
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование проекта')),
                ('gp', models.CharField(max_length=100, verbose_name='ГП')),
                ('year', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='ФИО слесаря')),
                ('job_title', models.CharField(max_length=100, verbose_name='Должность')),
                ('organization', models.CharField(max_length=100, verbose_name='Организация')),
            ],
            options={
                'verbose_name_plural': 'Слесарь',
            },
        ),
        migrations.CreateModel(
            name='DefectAct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defect_act', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='acts', to='device.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, verbose_name='Серийный номер')),
                ('gp', models.CharField(default='none', max_length=50, verbose_name='Поз. по ГП')),
                ('location', models.CharField(max_length=255, verbose_name='Место установки')),
                ('tag', models.CharField(blank=True, max_length=50, verbose_name='Тэг')),
                ('defect_act', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Номер деффектного акта')),
                ('project', models.CharField(max_length=100, verbose_name='Наименование проекта')),
                ('short_description', models.TextField(verbose_name='Краткое описание деффекта')),
                ('causes', models.TextField(verbose_name='Причина отказа')),
                ('status', models.TextField(verbose_name='Статус')),
                ('fix', models.TextField(default='None', verbose_name='Что требуется для устранения')),
                ('operating_time', models.SmallIntegerField(verbose_name='Время наработки')),
                ('invest_letter', models.CharField(max_length=255, verbose_name='Номер письма в Инвест')),
                ('at_date', models.DateTimeField(auto_now=True, verbose_name='Дата добавления')),
                ('approve', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='approve', to='defect.approve', verbose_name='Утверждающий')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='contractor', to='defect.contractor', verbose_name='Подрядчик')),
                ('defect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='equipment', to='device.equipment')),
                ('kait', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='kait', to='defect.kait', verbose_name='Мастер по КАиТ')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='worker', to='defect.worker', verbose_name='Мастер цеха')),
            ],
            options={
                'verbose_name_plural': 'Дефекты',
            },
        ),
    ]
